/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { registerHandlers } from "./handlers.js";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

export async function initializeServer() {
  const transport = new StdioServerTransport();

  const server = new Server(
    {
      name: "Account and Transaction API SpecificationLib",
      version: "1.0.0",
    },
    {
      capabilities: {
        tools: {}, // Indicate tool support is enabled
      },
    }
  );

  registerHandlers(server);

  await server.connect(transport);

  // Log that the server is running (to stderr to avoid interfering with stdio transport)
  console.error("Account and Transaction API SpecificationLib MCP Server running on stdio");
}

