/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AccountsController,
  BalancesController,
  BeneficiariesController,
  Client,
  DirectDebitsController,
  Environment,
  OffersController,
  PartyController,
  ScheduledPaymentsController,
  StandingOrdersController,
  StatementsController,
  TransactionsController,
  type Configuration,
} from 'account-and-transaction-api-specificationlib';

export const sdkClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.ACCOUNT_AND_TRANSACTION_API_SPECIFICATION_LIB_ENVIRONMENT;
  const timeout = process.env.ACCOUNT_AND_TRANSACTION_API_SPECIFICATION_LIB_TIMEOUT;
  const accessToken = process.env.ACCOUNT_AND_TRANSACTION_API_SPECIFICATION_LIB_ACCESS_TOKEN;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (accessToken !== undefined) {
    config.bearerAuthCredentials = { accessToken: accessToken };
  }

  return config;
}

export const accountsController = new AccountsController(sdkClient);
export const balancesController = new BalancesController(sdkClient);
export const beneficiariesController = new BeneficiariesController(sdkClient);
export const directDebitsController = new DirectDebitsController(sdkClient);
export const offersController = new OffersController(sdkClient);
export const partyController = new PartyController(sdkClient);
export const scheduledPaymentsController = new ScheduledPaymentsController(sdkClient);
export const standingOrdersController = new StandingOrdersController(sdkClient);
export const statementsController = new StatementsController(sdkClient);
export const transactionsController = new TransactionsController(sdkClient);

