/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  type Tool,
  type CallToolResult,
} from '@modelcontextprotocol/sdk/types.js';
import { getAccountTool } from './accounts/getAccount.js';
import { getAccountsTool } from './accounts/getAccounts.js';
import { getAccountBalancesTool } from './balances/getAccountBalances.js';
import { getBalancesTool } from './balances/getBalances.js';
import { getAccountBeneficiariesTool } from './beneficiaries/getAccountBeneficiaries.js';
import { getBeneficiariesTool } from './beneficiaries/getBeneficiaries.js';
import { getAccountDirectDebitsTool } from './directDebits/getAccountDirectDebits.js';
import { getDirectDebitsTool } from './directDebits/getDirectDebits.js';
import { getAccountOffersTool } from './offers/getAccountOffers.js';
import { getOffersTool } from './offers/getOffers.js';
import { getAccountPartyTool } from './party/getAccountParty.js';
import { getPartyTool } from './party/getParty.js';
import { getAccountScheduledPaymentsTool } from './scheduledPayments/getAccountScheduledPayments.js';
import { getScheduledPaymentsTool } from './scheduledPayments/getScheduledPayments.js';
import { getAccountStandingOrdersTool } from './standingOrders/getAccountStandingOrders.js';
import { getStandingOrdersTool } from './standingOrders/getStandingOrders.js';
import { getAccountStatementTool } from './statements/getAccountStatement.js';
import { getAccountStatementFileTool } from './statements/getAccountStatementFile.js';
import { getAccountStatementsTool } from './statements/getAccountStatements.js';
import { getAccountStatementTransactionsTool } from './statements/getAccountStatementTransactions.js';
import { getStatementsTool } from './statements/getStatements.js';
import { getAccountTransactionsTool } from './transactions/getAccountTransactions.js';
import { getTransactionsTool } from './transactions/getTransactions.js';


export type ToolDefinition = {
  tool: Tool;
  handler: (arg: unknown) => Promise<CallToolResult>;
};

// Export all defined tools in an array
export const allTools: Record<string, ToolDefinition> = {
  'accounts-getAccount': getAccountTool,
  'accounts-getAccounts': getAccountsTool,
  'balances-getBalances': getBalancesTool,
  'balances-getAccountBalances': getAccountBalancesTool,
  'beneficiaries-getAccountBeneficiaries': getAccountBeneficiariesTool,
  'beneficiaries-getBeneficiaries': getBeneficiariesTool,
  'directDebits-getAccountDirectDebits': getAccountDirectDebitsTool,
  'directDebits-getDirectDebits': getDirectDebitsTool,
  'offers-getAccountOffers': getAccountOffersTool,
  'offers-getOffers': getOffersTool,
  'party-getAccountParty': getAccountPartyTool,
  'party-getParty': getPartyTool,
  'scheduledPayments-getAccountScheduledPayments': getAccountScheduledPaymentsTool,
  'scheduledPayments-getScheduledPayments': getScheduledPaymentsTool,
  'standingOrders-getAccountStandingOrders': getAccountStandingOrdersTool,
  'standingOrders-getStandingOrders': getStandingOrdersTool,
  'statements-getAccountStatement': getAccountStatementTool,
  'statements-getAccountStatementFile': getAccountStatementFileTool,
  'statements-getAccountStatementTransactions': getAccountStatementTransactionsTool,
  'statements-getAccountStatements': getAccountStatementsTool,
  'statements-getStatements': getStatementsTool,
  'transactions-getAccountTransactions': getAccountTransactionsTool,
  'transactions-getTransactions': getTransactionsTool,
}
